[package]
name = "rust_pwtool"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1", features = ["derive"] }
sha2 = "0.10"
md5 = "0.7"
rayon = "1.7"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
